query Posts {
	posts {
		nodes {
			id
			title
			dateGmt
			slug
			excerpt(format: RAW)
			featuredImage {
				node {
					id
					sourceUrl
					altText
				}
			}
			tags {
				edges {
					node {
						id
						name
					}
				}
			}
			author {
				node {
					name
				}
			}
		}
	}
}
