query SinglePostBySlug($slug: ID!) {
	post(id: $slug, idType: SLUG) {
		id
		title
		dateGmt
		blocks {
			attributesJSON
			name
			innerBlocks {
				attributesJSON
				name
				innerBlocks {
					attributesJSON
					name
					innerBlocks {
						attributesJSON
						name
						innerBlocks {
							attributesJSON
							name
						}
					}
				}
			}
		}
		featuredImage {
			node {
				id
				sourceUrl
				altText
			}
		}
		date
		slug
		tags {
			edges {
				node {
					id
					name
				}
			}
		}
		author {
			node {
				name
			}
		}
	}
}
