query SinglePostBySlug($slug: String!) {
	postBy(slug: $slug) {
		id
		title
		blocks {
			attributesJSON
			name
			innerBlocks {
				attributesJSON
				name
				innerBlocks {
					attributesJSON
					name
					innerBlocks {
						attributesJSON
						name
						innerBlocks {
							attributesJSON
							name
						}
					}
				}
			}
		}
		date
		slug
		tags {
			edges {
				node {
					id
					name
				}
			}
		}
		author {
			node {
				name
			}
		}
	}
}
