query SinglePageByUri($uri: ID!) {
	page(id: $uri, idType: URI) {
		id
		title
		isFrontPage
		blocks {
			attributesJSON
			name
			innerBlocks {
				attributesJSON
				name
				innerBlocks {
					attributesJSON
					name
					innerBlocks {
						attributesJSON
						name
						innerBlocks {
							attributesJSON
							name
						}
					}
				}
			}
		}
	}
}
