#import "~/components/_graphql/PostBase.fragment.gql"

fragment ProjectListItem on Project {
	...PostBase
	tags {
		edges {
			node {
				id
				name
			}
		}
	}
	featuredImage {
		node {
			id
			sourceUrl
			altText
		}
	}
}
